openapi: 3.0.3
info:
    title: Bookstore API
    description: An api that returns data about books in a bookstore
    version: 1.0.0
servers:
    - url: http://localhost:8080
paths:
    /books:
        get:
            tags:
                - books
            summary: getBooks books
            operationId: books#getBooks
            parameters:
                - name: title
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: zxl
                    minLength: 1
                  example: vyj
                - name: author
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: x
                    minLength: 1
                  example: 7r
                - name: publishedAt
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: "2007-10-03"
                    format: date
                  example: "2013-01-12"
                - name: published_after
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: "1970-05-26"
                    format: date
                  example: "2001-01-11"
                - name: published_before
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: "1982-07-17"
                    format: date
                  example: "1971-11-24"
                - name: limit
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: integer
                    example: 1484183840119250216
                    format: int64
                  example: 3578128365358530591
                - name: offset
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: integer
                    example: 12840632429852050069
                    format: int64
                  example: 11651147724402205983
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Book'
                                example:
                                    - author: Optio dolorem.
                                      cover_url: Dolorem quia.
                                      id: 3374331773824625157
                                      publishedAt: "1997-09-18"
                                      title: Nemo voluptates eum ut deserunt temporibus at.
                                    - author: Optio dolorem.
                                      cover_url: Dolorem quia.
                                      id: 3374331773824625157
                                      publishedAt: "1997-09-18"
                                      title: Nemo voluptates eum ut deserunt temporibus at.
                            example:
                                - author: Optio dolorem.
                                  cover_url: Dolorem quia.
                                  id: 3374331773824625157
                                  publishedAt: "1997-09-18"
                                  title: Nemo voluptates eum ut deserunt temporibus at.
                                - author: Optio dolorem.
                                  cover_url: Dolorem quia.
                                  id: 3374331773824625157
                                  publishedAt: "1997-09-18"
                                  title: Nemo voluptates eum ut deserunt temporibus at.
                                - author: Optio dolorem.
                                  cover_url: Dolorem quia.
                                  id: 3374331773824625157
                                  publishedAt: "1997-09-18"
                                  title: Nemo voluptates eum ut deserunt temporibus at.
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - books
            summary: createBook books
            operationId: books#createBook
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateBookRequestBody'
                        example:
                            author: Eum esse.
                            publishedAt: "2011-11-11"
                            title: Quia rerum odit amet.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Book'
                            example:
                                author: Est eum et reprehenderit deleniti ut voluptas.
                                cover_url: Neque possimus doloremque.
                                id: 7196923411108578318
                                publishedAt: "1985-07-01"
                                title: Neque eum quaerat ipsam et.
                "400":
                    description: 'invalid_input: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "409":
                    description: 'conflict: Conflict response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /books/{id}:
        delete:
            tags:
                - books
            summary: deleteBook books
            operationId: books#deleteBook
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  schema:
                    type: integer
                    description: ID of the book
                    example: 5574627245609559921
                    format: int64
                  example: 8828410291201230889
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - books
            summary: getBook books
            operationId: books#getBook
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  schema:
                    type: integer
                    description: ID of the book
                    example: 1358352904264507319
                    format: int64
                  example: 8477452422459716713
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Book'
                            example:
                                author: Qui nesciunt.
                                cover_url: Et cumque.
                                id: 7227316530711330698
                                publishedAt: "2002-01-20"
                                title: Illo at.
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        patch:
            tags:
                - books
            summary: updateBook books
            operationId: books#updateBook
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  schema:
                    type: integer
                    description: ID of the book
                    example: 524251577701104994
                    format: int64
                  example: 7652078690695299061
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateBookRequestBody'
                        example:
                            author: Eaque beatae natus amet dolor a et.
                            publishedAt: "1998-09-28"
                            title: Ut non ab repellat sed architecto laborum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Book'
                            example:
                                author: Non odit nisi corrupti dignissimos.
                                cover_url: Et et in exercitationem facilis.
                                id: 2280955852903502164
                                publishedAt: "1973-10-19"
                                title: Et at neque quaerat ad inventore velit.
                "400":
                    description: 'invalid_input: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "409":
                    description: 'conflict: Conflict response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /books/{id}/cover:
        put:
            tags:
                - books
            summary: setBookCover books
            operationId: books#setBookCover
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  schema:
                    type: integer
                    description: ID of the book
                    example: 7072469533959259698
                    format: int64
                  example: 6781663944315393717
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            $ref: '#/components/schemas/SetBookCoverRequestBody'
                        example:
                            cover:
                                - 69
                                - 115
                                - 116
                                - 32
                                - 115
                                - 105
                                - 109
                                - 105
                                - 108
                                - 105
                                - 113
                                - 117
                                - 101
                                - 32
                                - 97
                                - 117
                                - 116
                                - 32
                                - 97
                                - 117
                                - 116
                                - 46
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Book'
                            example:
                                author: Non autem hic consequatur.
                                cover_url: Natus eos aut odit voluptate id tempore.
                                id: 8122964174669253699
                                publishedAt: "2013-11-09"
                                title: Temporibus voluptatem debitis possimus.
                "400":
                    description: 'invalid_image_format: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "413":
                    description: 'payload_too_large: Request Entity Too Large response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /openapi.json:
        get:
            tags:
                - books
            summary: Download ./gen/http/openapi3.json
            operationId: books#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /swagger:
        get:
            tags:
                - books
            summary: Download ./public/swagger.html
            operationId: books#/swagger
            responses:
                "200":
                    description: File downloaded
    /uploads/covers/{path}:
        get:
            tags:
                - books
            summary: Download ./uploads/covers
            operationId: books#/uploads/covers/{path}
            parameters:
                - name: path
                  in: path
                  description: Relative file path
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: File downloaded
                "404":
                    description: File not found
components:
    schemas:
        Book:
            type: object
            properties:
                author:
                    type: string
                    example: Voluptates provident.
                cover_url:
                    type: string
                    example: Asperiores dolores molestiae qui suscipit.
                id:
                    type: integer
                    example: 6193106917263990956
                    format: int64
                publishedAt:
                    type: string
                    example: "2013-11-02"
                    format: date
                title:
                    type: string
                    example: Non omnis sit quis amet.
            description: A single book
            example:
                author: Voluptas repellat similique.
                cover_url: Facilis nisi iure quibusdam officiis cumque laudantium.
                id: 176858279221878788
                publishedAt: "1984-09-24"
                title: Id itaque temporibus.
            required:
                - id
                - title
                - author
                - publishedAt
        CreateBookRequestBody:
            type: object
            properties:
                author:
                    type: string
                    description: Author of the book
                    example: Eius id blanditiis dignissimos et ipsam.
                publishedAt:
                    type: string
                    description: Publication time of the book
                    example: "1989-12-16"
                    format: date
                title:
                    type: string
                    description: Title of the book
                    example: Saepe quia placeat deserunt facere sapiente ad.
            example:
                author: Quisquam quae.
                publishedAt: "2004-04-25"
                title: Sequi amet repellat et ducimus minus.
            required:
                - title
                - author
                - publishedAt
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        SetBookCoverRequestBody:
            type: object
            properties:
                cover:
                    type: string
                    description: Book cover image
                    example:
                        - 80
                        - 111
                        - 114
                        - 114
                        - 111
                        - 32
                        - 105
                        - 112
                        - 115
                        - 97
                        - 32
                        - 97
                        - 117
                        - 116
                        - 101
                        - 109
                        - 46
                    format: binary
            example:
                cover:
                    - 82
                    - 101
                    - 99
                    - 117
                    - 115
                    - 97
                    - 110
                    - 100
                    - 97
                    - 101
                    - 32
                    - 101
                    - 120
                    - 99
                    - 101
                    - 112
                    - 116
                    - 117
                    - 114
                    - 105
                    - 32
                    - 118
                    - 105
                    - 116
                    - 97
                    - 101
                    - 32
                    - 113
                    - 117
                    - 97
                    - 101
                    - 46
            required:
                - cover
        UpdateBookRequestBody:
            type: object
            properties:
                author:
                    type: string
                    description: Author of the book
                    example: Accusantium et.
                publishedAt:
                    type: string
                    description: Publication time of the book
                    example: "1980-09-30"
                    format: date
                title:
                    type: string
                    description: Title of the book
                    example: Ab deserunt reiciendis ut et est reiciendis.
            example:
                author: Doloribus eum et qui.
                publishedAt: "2007-11-20"
                title: Qui hic beatae neque et quibusdam.
tags:
    - name: books
      description: Service that returns data about books
